#!/bin/sh
code --install-extension BazelBuild.vscode-bazel
code --install-extension bungcip.better-toml
code --install-extension Dart-Code.dart-code
code --install-extension dbaeumer.vscode-eslint        
code --install-extension dunstontc.dark-plus-syntax    
code --install-extension dzhavat.css-flexbox-cheatsheet
code --install-extension esbenp.prettier-vscode        
code --install-extension Gimly81.matlab
code --install-extension goessner.mdmath
code --install-extension maelvalais.autoconf
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-azurefunctions
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.csharp
code --install-extension octref.vetur
code --install-extension QassimFarid.ejs-language-support
code --install-extension rust-lang.rust
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension stylelint.vscode-stylelint
code --install-extension sysoev.language-stylus
code --install-extension toba.vsfire
code --install-extension vscode-icons-team.vscode-icons
code --install-extension yzhang.markdown-all-in-one
