#!/bin/sh
code --install-extension auchenberg.vscode-browser-preview
code --install-extension BazelBuild.vscode-bazel
code --install-extension be5invis.toml
code --install-extension dbaeumer.vscode-eslint
code --install-extension esbenp.prettier-vscode
code --install-extension fallenwood.vimL
code --install-extension Gimly81.matlab
code --install-extension goessner.mdmath
code --install-extension henriiik.vscode-perl
code --install-extension johnpapa.vscode-peacock
code --install-extension maelvalais.autoconf
code --install-extension mathiasfrohlich.Kotlin
code --install-extension mhmadhamster.postcss-language
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension MS-CEINTL.vscode-language-pack-ja
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.Go
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-audio
code --install-extension ms-vsliveshare.vsliveshare-pack
code --install-extension octref.vetur
code --install-extension rust-lang.rust
code --install-extension shinnn.stylelint
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension stylelint.vscode-stylelint
code --install-extension toba.vsfire
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vncz.vscode-apielements
code --install-extension vscode-icons-team.vscode-icons
code --install-extension yzhang.markdown-all-in-one
