#!/bin/sh
code --install-extension auchenberg.vscode-browser-preview
code --install-extension be5invis.toml
code --install-extension dbaeumer.vscode-eslint
code --install-extension esbenp.prettier-vscode
code --install-extension fallenwood.vimL
code --install-extension Gimly81.matlab
code --install-extension goessner.mdmath
code --install-extension henriiik.vscode-perl
code --install-extension maelvalais.autoconf
code --install-extension mhmadhamster.postcss-language
code --install-extension mikestead.dotenv
code --install-extension MS-CEINTL.vscode-language-pack-ja
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.Go
code --install-extension octref.vetur
code --install-extension PeterJausovec.vscode-docker
code --install-extension shinnn.stylelint
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension vscode-icons-team.vscode-icons
code --install-extension yzhang.markdown-all-in-one
